# Generated by Django 2.1.2 on 2018-10-31 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('nome', models.CharField(max_length=100)),
                ('dt_Nascimento', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('Foto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('plano_ensino', models.CharField(max_length=200, null=True)),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(3)])),
                ('competencias', models.CharField(max_length=300, null=True)),
                ('habilidades', models.CharField(max_length=300, null=True)),
                ('ementa', models.CharField(max_length=500, null=True)),
                ('conteudo_prog', models.CharField(max_length=100, null=True)),
                ('bibli_basica', models.CharField(max_length=200, null=True)),
                ('bibli_compl', models.CharField(max_length=200, null=True)),
                ('percent_prat', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('percent_teo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('nome_cood', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=30, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(3)])),
                ('dt_Nascimento', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
    ]
